#!/bin/bash -e

eval "$(cli-shezargs $@)"

ra_invoke() {
  ra invoke "$@"
  echo -n ', '
}

if [[ -n $workstation ]]; then
  uri_base="$(echo $uri_base | sed s/$domain_name/mobilewebassist.net/)"
  uri_test_base="$()"
  deploy_style="justX"
  deploy_args="${project_id}.prod"
fi

ra_invoke ./models/project.js upsertProject --project-id="${project_id}" --top-ns="${top_ns}" \
      --domain-name="${domain_name}" \
      --test-domain-name="${test_domain_name}" \
      --deploy-style="${deploy_style}" \
      --deploy-args="${deploy_args}" \
      --aws-dev-key="${aws_dev_key}" --aws-prod-key="${aws_prod_key}" --aws-hq-key="${aws_hq_key}" \
      --bucket-namespace="${bucket_namespace}" \
      --cluster-class-b="${cluster_class_b}" --test-class-b="${test_class_b}" --prod-class-b="${prod_class_b}" \
      --uri-base="${uri_base}"

