#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -z $service ]] && service="$SERVERASSIST_SERVICE"

if jsaws-build-block "install-repos" "Install repos"; then

  if ! [[ -d ${HOME}/dev/serverassist ]]; then
    mkdir -p ${HOME}/dev && cd $_

    (git clone git@github.com:briancsparks/js-cluster.git   && cd js-cluster   &&                          npm install --production)
    (git clone git@github.com:briancsparks/serverassist.git && cd serverassist &&                          npm install --production)

    (git clone git@github.com:briancsparks/server-assist-server.git)

    if [[ $service == web ]]; then

      (cd server-assist-server          && npm install --production)
      (cd server-assist-server/webtier  && npm install --production)
      (cd server-assist-server/hq       && npm install --production)
    fi

    if [[ $service == netapp ]]; then
      (cd server-assist-server/s3       && npm install --production)

      (git clone git@github.com:briancsparks/attr-man                       && cd attr-man          && npm install --production)
#      (git clone git@github.com:briancsparks/netlab-telemetry               && cd netlab-telemetry  && npm install --production)
      (git clone git@github.azc.ext.hp.com:MobileApps/Netlab_Telemetry      && cd Netlab_Telemetry  && npm install --production)
      (git clone git@github.com:briancsparks/mario-sys-viewer)
    fi

    if [[ $service == watchdog ]]; then
      (cd server-assist-server/sa-watchdog       && npm install --production)

      (git clone git@github.azc.ext.hp.com:MobileApps/Netlab_Telemetry      && cd Netlab_Telemetry/sa-watchdog  && npm install --production)
    fi

    if [[ $service == admin ]]; then
      (git clone git@github.com:briancsparks/js-aws       && cd js-aws            && npm install)
      (git clone git@github.com:IPGPTP/mario-js           && cd mario-js          && npm install)
      (git clone git@github.com:briancsparks/sg           && cd sg                && npm install)
    fi

  fi

  jsaws-build-block "install-repos" "done"
fi

if jsaws-build-block "nessus" "Install Nessus Scanner"; then
  cd ~/zz_packages

  aws s3 cp "s3://${SERVERASSIST_BUILDOUT_BUCKET}/buildout/packages/NessusAgent-6.10.7-ubuntu1110_amd64.deb" ./
  sudo dpkg -i "$(find ./ -maxdepth 1 -type f | egrep 'NessusAgent.*\.deb$')"
  jsaws-build-block "nessus" "done"
fi

