#!/bin/bash -e

script_dir="$(dirname $0)"

scripts="$(ls $script_dir | egrep '^[0-9][0-9]' | egrep -v aa-build-all | sort)"

for script in $scripts; do
  echo "--------------------------------------------------------------------------------------------- ${script_dir}/$script $@"
  ${script_dir}/${script} "$@"

done

