#!/bin/bash -e

# TODO: set env vars for running stackname, db, util, color

jsaws-set-env SERVERASSIST_MY_IP "$(curl -s 'http://169.254.169.254/latest/meta-data/local-ipv4')"

my_keyname="$(curl -s http://169.254.169.254/latest/meta-data/public-keys/ | cut -d= -f2)"
if [[ $my_keyname =~ prod ]]; then
  jsaws-set-env NODE_ENV production
else
  jsaws-set-env NODE_ENV development
fi


