#!/bin/bash -e

# TODO: set env vars for running stackname, db, util, color

eval "$(cli-shezargs $@)"

# Let the code from js-cluster do its start-from-snapshot code
(cd ${scripts_dir}/../../build/on-instance && ./b01-start-from-snapshot)

