#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -z $service ]] && service="$SERVERASSIST_SERVICE"
[[ -z $stack   ]] && stack="$SERVERASSIST_STACK"

# Get the webtier script running, it causes the nginx.conf file to be generated
if [[ $service == web ]]; then
  (cd ~/dev/server-assist-server/webtier && pm2 start webtier.js -- --verbose --main)
fi

# Let the code from js-cluster do its start-services code
(cd ${scripts_dir}/../../build/on-instance && ./b02-start-services)

# Now do our other services for the webtier
if [[ $service == web ]]; then

  if [[ $stack == cluster ]]; then
    (cd ~/dev/server-assist-server/hq      && pm2 start hq.js      -- --verbose --main)
    (cd ~/dev/server-assist-server/console && pm2 start console.js -- --verbose --main)
  fi
fi


if [[ $service == netapp ]]; then
  (cd ~/dev/attr-man && pm2 start attr-man.js -- --verbose --main)
fi

