#!/bin/bash -e

eval "$(cli-shezargs $@)"

for ip in "$@"; do
  echo "--- $ip"
  sshix $ip '[[ -f build-scripts/on-instance/z01-pre-terminate ]] && build-scripts/on-instance/z01-pre-terminate || true'
done

for ip in "$@"; do
  echo "--- $ip"
  instance_id="$(sshix $ip 'curl -sS http://169.254.169.254/latest/meta-data/instance-id')"

  aws ec2 terminate-instances --instance-ids $instance_id

done

